version: '3'

services:
  backend:
    build: .
    ports:
      - 8090:8080
    volumes:
      - .:/usr/src/app
    command: npm run dev
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
      - /app/node_modules
    command: npm start
    environment:
      - WATCHPACK_POLLING=true
